theme: jekyll-theme-minimal
logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Falldus.com%2Fblog%2Fcareer-advice%2Fskills-needed-for-a-career-in-bioinformatics%2F&psig=AOvVaw29vwVMrk4xsePiFm24NS9J&ust=1638829375589000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJi3ybDZzfQCFQAAAAAdAAAAABAJ
title: Jibin's Bioinfomatics Class (BGGN213, Fall 2021)
