theme: jekyll-theme-minimal
logo: https://alldus.com/media/2302/shutterstock_671206525-min.jpg?anchor=center&mode=crop&width=1600&height=900&quality=75
title: Jibin's Bioinfomatics Class (BGGN213, Fall 2021)
